library(rtweet)
library(ggplot2)
library(tidyverse)
auth <- rtweet_app()
tmls <- get_timelines(c("ChineseEmbinUS"), n = 100)
tmls = data.frame(lapply(tmls, as.character), stringsAsFactors=FALSE)
write.csv(tmls, file = "tweeps/export/burpy.csv")
